# Docker Compose Configuration for Roman Numeral Converter
#
# This configuration sets up a development environment with:
# - Backend API server (Node.js/Express)
# - Frontend UI (React)
#
# @author Interview Candidate
# @version 1.0.0

version: '3.7'

services:
  # Backend API Service
  # Provides the Roman numeral conversion REST API
  backend:
    build: ./backend
    ports:
      - "3001:3001"  # Expose API on port 3001

  # Frontend UI Service
  # Provides the React application for the Roman numeral converter
  frontend:
    build: ./frontend
    ports:
      - '5173:80'
    environment:
      - NODE_ENV=production 
